//
//  StyleKit.swift
//  Grid Capture
//
//  Created by Ben Rohel on 29/04/2016.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import AppKit



class StyleKit: NSObject {
    
    
    //MARK: - Colors
    
    static let leftMenu = NSColor(hue: 0.594, saturation: 0.34, brightness: 0.369, alpha: 1)
    static let oval15Copy3 = NSColor(hue: 0.619, saturation: 0.292, brightness: 0.282, alpha: 1)
    static let on = NSColor(hue: 0.29, saturation: 0.506, brightness: 0.922, alpha: 1)
    static let standbye = NSColor(hue: 0.109, saturation: 0.506, brightness: 0.922, alpha: 1)
    static let off = NSColor(hue: 1, saturation: 0.506, brightness: 0.922, alpha: 1)
    static let oval15Copy9 = NSColor(hue: 0.8, saturation: 0.506, brightness: 0.922, alpha: 1)
    static let oval15Copy10 = NSColor(hue: 0.648, saturation: 0.506, brightness: 0.922, alpha: 1)
    static let oval15Copy4 = NSColor(white: 0.996, alpha: 1)
    static let rightMenu = NSColor(hue: 0.614, saturation: 0.262, brightness: 0.329, alpha: 1)
    static let bg_subMenu = NSColor(hue: 0.627, saturation: 0.213, brightness: 0.314, alpha: 1)
    static let selected = NSColor(hue: 0.61, saturation: 0.678, brightness: 1, alpha: 1)
    static let bgBar = NSColor(hue: 0.679, saturation: 0.099, brightness: 0.557, alpha: 1)
    static let separator = NSColor(hue: 0.667, saturation: 0.028, brightness: 0.557, alpha: 0.44)
    
}
//MARK: - Round Buttons






